### ISSUE TITLE
Limit "visible" trigger to fire only once

### ISSUE THREAD

**Issue by mbaersch** [elbwalker/walker.js#114]
I am just getting started to use walker.js in a project and ran into something that might be a feature request for the *visible* trigger: AFAIK this trigger always fires, whenever the element appears in the viewport for at least 50% and one second. Which might be the case more than once if a user scrolls up and down a page.    

I would prefer to send this event only once per page and element instead. Is there a way to achieve that already? If not, an optional parameter would be great. Some boolean for a "unique" invocation like `data-elbaction="visible(true):view"` could be a solution (default would be "false" in case there is no parameter).

**Comment by alexanderkirtzel** [comment]
The visible trigger behaves as you wish: It only fires once per run under that conditions.
Yes, there is some kind of inconsistency in wordings, click fires multiple times, while visible does only once.
But I like your suggestion of introducing parameters to the visible trigger `data-elbaction="visible(multiple)"` to support multiple firing (not the best wording yet).

Can this issue be closed since it's working as wished?

PS: Welcome :)

**Comment by mbaersch** [comment]
Hm. Then I have a test page that shows different behavior and might be helpful for debugging. Feel free to close this issue - I can share details via PM if you wish to take a look at what happens in my case. You know where to find me ;)

**Comment by alexanderkirtzel** [comment]
Let's have a look and if it's also relevant for others I'll share it
