### ISSUE TITLE
optionally capture referrer 

### ISSUE THREAD

**Issue by mbaersch** [elbwalker/walker.js#115]
**Is your feature request related to a problem? Please describe.**
Using walker.js on a website for collecting first party data by sending every event to a custom endpoint always needs manual addition of a referrer in order to enable channel attribution for the collected events. 

**Describe the solution you'd like**
It would be great if walker.js would capture a referrer without manual action beyond configuration. This should be an optional feature which is not enabled by default. Otherwise existing setups that capture the whole event would pay with increased storage costs. 

The automatic collection could be added to the event data (in case of an page view or other events as well) or globals by setting an option. A choice between capturing only external referrers (for attribution) and all referrers might be useful, too.  

**Describe alternatives you've considered**
At the moment it seems to be the only option to add the referrer as a DOM element before walker initialization or by code when using elb() function.

**Comment by alexanderkirtzel** [comment]
Good point! As of now, the auto page view event has these properties:

domain, // location.hostname
id, // location.pathname
title, // document.title
search, // location.search (optional)
hash // location.hash (optional)

I'd suggest just adding the referrer property since additional configuration might blow up settings, size, and confusion why there are no further settings for other properties. One could decide not to use it.

There are two possible ways:

1. just use the `document.referrer` value as it is provided by the browser
2. do some basic logic in terms of interpreting it (use "unknown" for an empty referrer, use "internal" if it's the same as the domain, and only use the hostname to be consistent with the domain property)

What would you prefer?

**Comment by mbaersch** [comment]
hard to answer. I guess the first option yields the expected values but could lead to a maximum of additional stored bytes ( = costs). The second one looks like a balanced option... but might lead to questions. I would prefer the second solution (but this is n=1 ;))

**Comment by alexanderkirtzel** [comment]
There are some advantages to just using the browsers `document.referrer`. The walker provides all necessary information while a destination decides how to deal with it. A page view event simply has a referrer.

But I'll also follow the second version. I was thinking about an optional **session start** event as well. And this one would not just interpret the referrer as described, but also parse UTM parameters e.g. In combination, this could have some great benefits without blowing up the code while offering great possibilities.

**Comment by mbaersch** [comment]
> But I'll also follow the second version. I was thinking about an optional **session start** event as well. And this one would not just interpret the referrer as described, but also parse UTM parameters e.g. In combination, this could have some great benefits without blowing up the code while offering great possibilities.

Parsing referrer and url to something like a "source/medium" information can be useful, but... identifying a new session seems an odd feature for a script that needs user and  / or session information provided via individual implementation. And using a limited (and never complete) set of known url parameters that indicate a new session start can not fulfill this task for every use case. I would just add the referrer and let developers decide if and when a session start needs to be detected in the browser. Most tools - except GA4 - do not need this anyway(?)
